export const MODAL_TYPE_CHART = 'CHART_MODAL';
export const MODAL_TYPE_OTHER = 'OTHER_MODAL';
export const MODAL_TYPE_SIGNIN = 'SIGNIN_MODAL';
export const MODAL_TYPE_SIGNUP = 'SIGNUP_MODAL';
export const MODAL_TYPE_FORGOTPASSWORD = 'FORGOTPASSWORD_MODAL';
